buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
    }
}

ext {
    apiVersion = 35
    compilerVersion = '25.0.1'
    supportLibraryVersion = '25.1.0'
    playLibraryVersion = '17.0.0'
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://jitpack.io"
        }
        maven {
            url 'https://maven.batch.com/release'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
