apply plugin: 'com.android.application'

//noinspection GroovyMissingReturnStatement
android {
    compileSdkVersion apiVersion
    buildToolsVersion compilerVersion
    namespace = "uk.co.jakelee.cityflow"

    defaultConfig {
        applicationId "uk.co.jakelee.cityflow"
        minSdkVersion 21
        targetSdkVersion apiVersion
        versionCode 19
        versionName "1.1.1"
        multiDexEnabled true
    }
    buildFeatures {
        buildConfig = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.pro'
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://maven.batch.com/release'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':BaseGameUtils')
    implementation 'com.github.satyan:sugar:1.5'
    implementation 'com.google.code.gson:gson:2.6.2'
    implementation 'com.thomashaertel:multispinner:0.1.1'
    implementation 'com.scottyab:aescrypt:0.0.1'
    implementation "com.android.support:appcompat-v7:$supportLibraryVersion"
    implementation "com.android.support:design:$supportLibraryVersion"
    implementation "com.android.support:percent:$supportLibraryVersion"
    implementation "com.google.android.gms:play-services-auth:$playLibraryVersion"
    implementation "com.google.android.gms:play-services-games:$playLibraryVersion"
    implementation "com.google.android.gms:play-services-gcm:$playLibraryVersion"
    implementation "com.google.android.gms:play-services-vision:17.0.2"
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.github.hotchemi:android-rate:1.0.1'
    implementation 'me.grantland:autofittextview:0.2.1'
    implementation 'de.keyboardsurfer.android.widget:crouton:1.8.5@aar'
    implementation 'com.anjlab.android.iab.v3:library:2.2.0'
    implementation 'com.google.zxing:core:3.2.1'
    implementation 'com.github.aitorvs:allowme:0.3.2'
    implementation 'com.batch.android:batch-sdk:1.7+'

    implementation files('libs/applovin-sdk-6.3.0.jar')
}
